<?php

$YOUR_VERIFICATION_TOKEN = 'tokensample1';
$YOUR_PAGE_TOKEN_HERE = 'EAAD9mW8bfvUBAH7NZAbGSITWkOPJV2pjBZC1SmswZAs8yj0ZBlUiWTypoc4C08gqt08sOK9Gng7fHsRPNNVHp2Ke297xaTjGgDzSDOiaBLRsDIZAo06YMEzPNDWQ8xs35YtX4xvoVAfaCp9XsC3ORTZAxY8LSqygYZD';


return [
'verify_token' => $YOUR_VERIFICATION_TOKEN,
'token' => $YOUR_PAGE_TOKEN_HERE
];